name: PR Merge Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0 # matching Elctron's (20.X) version of node
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Identity
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '<${{ github.actor }}@users.noreply.github.com>'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Version
        run: yarn run version --yes

      - name: Commit
        run: |
          git add .
          git commit -am "Auto Versioning"
          git push
